default: &default
  adapter: postgresql
  username: postgresql
  password: postgresql
  host: localhost

development:
  <<: *default
  database: gamma_finances_dev

test:
  adapter: postgresql
  database: travis_ci_test
  username: postgres

production:
  <<: *default
  database: gamma_finances_production
